name: Build and Assert Assets Exists
description: Build the package and assert that file contents exist as we expect
runs:
  using: "composite"
  steps:
  - name: Build and Assert Output
    run: |-
      echo 'target: ember-headless-table/dist
      setup:
        run: pnpm run build:js
        cwd: ./ember-headless-table
      expect: |
        index.js
        index.js.map
        index.d.ts
        plugins/index.js
        plugins/data-sorting/index.js
        plugins/column-reordering/index.js
        plugins/column-resizing/index.js
        plugins/column-visibility/index.js
        plugins/sticky-columns/index.js
        test-support/index.js
      ' >> assert-contents.config.yml
      npx assert-folder-contents

  - name: Upload dist assets to cache
    uses: actions/upload-artifact@v3
    with:
      name: dist
      path: ${{ env.dist }}
